name: timeseries
dependencies:
  - matplotlib
  - numpy
  - pandas
  - pip
  - pip:
      - darts
      - skforecast
  - python=3.10
  - seaborn
  - scikit-learn
  - statsmodels
  - tqdm
  - structlog

channels:
  - conda-forge
